name: best_hundred_books
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #network
  provider: ^6.0.0
  vexana: ^2.3.0
  #model
  json_serializable: ^5.0.1
  json_annotation: ^4.1.0
  #ui
  auto_size_text: ^3.0.0-nullsafety.0
  font_awesome_flutter:
  webview_flutter: any
  #language
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/lang/
